// /app/lib/track-coordinates.ts
// Coordinates for iRacing tracks — matched by track_name

export interface TrackCoords {
  track_name: string;
  lat: number;
  lng: number;
  country: string;
  city?: string;
}

// Matched against iRacing track_name field (case-insensitive partial match)
export const TRACK_COORDS: TrackCoords[] = [
  // ── USA ─────────────────────────────────────────────────────
  {
    track_name: "Daytona International Speedway",
    lat: 29.1853,
    lng: -81.0694,
    country: "USA",
    city: "Daytona Beach, FL",
  },
  {
    track_name: "Indianapolis Motor Speedway",
    lat: 39.7954,
    lng: -86.2353,
    country: "USA",
    city: "Indianapolis, IN",
  },
  {
    track_name: "Talladega Superspeedway",
    lat: 33.5689,
    lng: -86.0637,
    country: "USA",
    city: "Talladega, AL",
  },
  {
    track_name: "Charlotte Motor Speedway",
    lat: 35.3525,
    lng: -80.6829,
    country: "USA",
    city: "Concord, NC",
  },
  {
    track_name: "Bristol Motor Speedway",
    lat: 36.5158,
    lng: -82.2574,
    country: "USA",
    city: "Bristol, TN",
  },
  {
    track_name: "Watkins Glen International",
    lat: 42.3369,
    lng: -76.9269,
    country: "USA",
    city: "Watkins Glen, NY",
  },
  {
    track_name: "Road Atlanta",
    lat: 34.1498,
    lng: -83.8143,
    country: "USA",
    city: "Braselton, GA",
  },
  {
    track_name: "Sebring International Raceway",
    lat: 27.4542,
    lng: -81.3487,
    country: "USA",
    city: "Sebring, FL",
  },
  {
    track_name: "Lime Rock Park",
    lat: 41.9278,
    lng: -73.3822,
    country: "USA",
    city: "Lime Rock, CT",
  },
  {
    track_name: "Laguna Seca",
    lat: 36.584,
    lng: -121.7535,
    country: "USA",
    city: "Monterey, CA",
  },
  {
    track_name: "WeatherTech Raceway Laguna Seca",
    lat: 36.584,
    lng: -121.7535,
    country: "USA",
    city: "Monterey, CA",
  },
  {
    track_name: "Circuit of the Americas",
    lat: 30.1328,
    lng: -97.6411,
    country: "USA",
    city: "Austin, TX",
  },
  {
    track_name: "Virginia International Raceway",
    lat: 36.5584,
    lng: -79.2068,
    country: "USA",
    city: "Alton, VA",
  },
  {
    track_name: "Road America",
    lat: 43.8005,
    lng: -87.9897,
    country: "USA",
    city: "Elkhart Lake, WI",
  },
  {
    track_name: "Pocono Raceway",
    lat: 41.0548,
    lng: -75.5124,
    country: "USA",
    city: "Long Pond, PA",
  },
  {
    track_name: "Phoenix Raceway",
    lat: 33.3745,
    lng: -112.3118,
    country: "USA",
    city: "Avondale, AZ",
  },
  {
    track_name: "Iowa Speedway",
    lat: 41.6587,
    lng: -93.0135,
    country: "USA",
    city: "Newton, IA",
  },
  {
    track_name: "Kansas Speedway",
    lat: 39.115,
    lng: -94.8308,
    country: "USA",
    city: "Kansas City, KS",
  },
  {
    track_name: "Michigan International Speedway",
    lat: 42.0647,
    lng: -84.2448,
    country: "USA",
    city: "Brooklyn, MI",
  },
  {
    track_name: "New Hampshire Motor Speedway",
    lat: 43.3617,
    lng: -71.4618,
    country: "USA",
    city: "Loudon, NH",
  },
  {
    track_name: "Richmond Raceway",
    lat: 37.5956,
    lng: -77.4215,
    country: "USA",
    city: "Richmond, VA",
  },
  {
    track_name: "Martinsville Speedway",
    lat: 36.6397,
    lng: -79.8522,
    country: "USA",
    city: "Martinsville, VA",
  },
  {
    track_name: "Atlanta Motor Speedway",
    lat: 33.3868,
    lng: -84.3219,
    country: "USA",
    city: "Hampton, GA",
  },
  {
    track_name: "Auto Club Speedway",
    lat: 34.092,
    lng: -117.4975,
    country: "USA",
    city: "Fontana, CA",
  },
  {
    track_name: "Darlington Raceway",
    lat: 34.2956,
    lng: -79.9073,
    country: "USA",
    city: "Darlington, SC",
  },
  {
    track_name: "Dover Motor Speedway",
    lat: 39.1895,
    lng: -75.5307,
    country: "USA",
    city: "Dover, DE",
  },
  {
    track_name: "Homestead-Miami Speedway",
    lat: 25.4519,
    lng: -80.4087,
    country: "USA",
    city: "Homestead, FL",
  },
  {
    track_name: "Las Vegas Motor Speedway",
    lat: 36.272,
    lng: -115.0108,
    country: "USA",
    city: "Las Vegas, NV",
  },
  {
    track_name: "Nashville Superspeedway",
    lat: 36.2023,
    lng: -86.3101,
    country: "USA",
    city: "Lebanon, TN",
  },
  {
    track_name: "Texas Motor Speedway",
    lat: 33.0368,
    lng: -97.2822,
    country: "USA",
    city: "Fort Worth, TX",
  },
  {
    track_name: "Superspeedway",
    lat: 33.5689,
    lng: -86.0637,
    country: "USA",
    city: "USA",
  },
  {
    track_name: "Summit Point Raceway",
    lat: 39.2478,
    lng: -77.985,
    country: "USA",
    city: "Summit Point, WV",
  },
  {
    track_name: "Pittsburgh International Race Complex",
    lat: 40.6116,
    lng: -80.3667,
    country: "USA",
    city: "Wampum, PA",
  },
  {
    track_name: "Mid-Ohio Sports Car Course",
    lat: 40.6898,
    lng: -82.6388,
    country: "USA",
    city: "Lexington, OH",
  },
  {
    track_name: "Sonoma Raceway",
    lat: 38.1607,
    lng: -122.455,
    country: "USA",
    city: "Sonoma, CA",
  },
  {
    track_name: "Gateway Motorsports Park",
    lat: 38.6408,
    lng: -90.1622,
    country: "USA",
    city: "Madison, IL",
  },
  {
    track_name: "Long Beach Street Circuit",
    lat: 33.7674,
    lng: -118.1929,
    country: "USA",
    city: "Long Beach, CA",
  },
  {
    track_name: "Nashville Street Circuit",
    lat: 36.1627,
    lng: -86.7816,
    country: "USA",
    city: "Nashville, TN",
  },
  {
    track_name: "Miami International Autodrome",
    lat: 25.958,
    lng: -80.2389,
    country: "USA",
    city: "Miami Gardens, FL",
  },
  {
    track_name: "St. Petersburg Grand Prix",
    lat: 27.7731,
    lng: -82.635,
    country: "USA",
    city: "St. Petersburg, FL",
  },
  {
    track_name: "Barber Motorsports Park",
    lat: 33.5558,
    lng: -86.7205,
    country: "USA",
    city: "Leeds, AL",
  },
  {
    track_name: "Portland International Raceway",
    lat: 45.5963,
    lng: -122.6941,
    country: "USA",
    city: "Portland, OR",
  },
  {
    track_name: "Belle Isle Park",
    lat: 42.3345,
    lng: -82.9938,
    country: "USA",
    city: "Detroit, MI",
  },
  {
    track_name: "Autodromo José Carlos Pace",
    lat: -23.7036,
    lng: -46.6997,
    country: "Brazil",
    city: "São Paulo",
  },
  // ── Europe ──────────────────────────────────────────────────
  {
    track_name: "Spa-Francorchamps",
    lat: 50.4372,
    lng: 5.9714,
    country: "Belgium",
    city: "Stavelot",
  },
  {
    track_name: "Circuit de Spa-Francorchamps",
    lat: 50.4372,
    lng: 5.9714,
    country: "Belgium",
    city: "Stavelot",
  },
  {
    track_name: "Nürburgring",
    lat: 50.3356,
    lng: 6.9475,
    country: "Germany",
    city: "Nürburg",
  },
  {
    track_name: "Nurburgring",
    lat: 50.3356,
    lng: 6.9475,
    country: "Germany",
    city: "Nürburg",
  },
  {
    track_name: "Hockenheimring",
    lat: 49.3278,
    lng: 8.5653,
    country: "Germany",
    city: "Hockenheim",
  },
  {
    track_name: "Silverstone Circuit",
    lat: 52.0786,
    lng: -1.0169,
    country: "UK",
    city: "Silverstone",
  },
  {
    track_name: "Brands Hatch",
    lat: 51.3572,
    lng: 0.2626,
    country: "UK",
    city: "Fawkham",
  },
  {
    track_name: "Donington Park",
    lat: 52.8306,
    lng: -1.375,
    country: "UK",
    city: "Castle Donington",
  },
  {
    track_name: "Oulton Park",
    lat: 53.1889,
    lng: -2.6025,
    country: "UK",
    city: "Tarporley",
  },
  {
    track_name: "Snetterton",
    lat: 52.4697,
    lng: 0.9592,
    country: "UK",
    city: "Norfolk",
  },
  {
    track_name: "Thruxton",
    lat: 51.2097,
    lng: -1.6003,
    country: "UK",
    city: "Andover",
  },
  {
    track_name: "Knockhill Racing Circuit",
    lat: 56.1183,
    lng: -3.4536,
    country: "UK",
    city: "Dunfermline",
  },
  {
    track_name: "Monza",
    lat: 45.6156,
    lng: 9.2811,
    country: "Italy",
    city: "Monza",
  },
  {
    track_name: "Autodromo Nazionale Monza",
    lat: 45.6156,
    lng: 9.2811,
    country: "Italy",
    city: "Monza",
  },
  {
    track_name: "Imola",
    lat: 44.3439,
    lng: 11.7167,
    country: "Italy",
    city: "Imola",
  },
  {
    track_name: "Mugello",
    lat: 43.9975,
    lng: 11.3719,
    country: "Italy",
    city: "Scarperia",
  },
  {
    track_name: "Vallelunga",
    lat: 42.1647,
    lng: 12.3783,
    country: "Italy",
    city: "Campagnano",
  },
  {
    track_name: "Misano World Circuit",
    lat: 43.9653,
    lng: 12.6833,
    country: "Italy",
    city: "Misano Adriatico",
  },
  {
    track_name: "Circuit de Barcelona-Catalunya",
    lat: 41.57,
    lng: 2.2611,
    country: "Spain",
    city: "Montmeló",
  },
  {
    track_name: "Barcelona",
    lat: 41.57,
    lng: 2.2611,
    country: "Spain",
    city: "Montmeló",
  },
  {
    track_name: "Circuit de Navarra",
    lat: 42.5383,
    lng: -1.6358,
    country: "Spain",
    city: "Navarra",
  },
  {
    track_name: "Jarama",
    lat: 40.6178,
    lng: -3.5831,
    country: "Spain",
    city: "Madrid",
  },
  {
    track_name: "Red Bull Ring",
    lat: 47.2197,
    lng: 14.7647,
    country: "Austria",
    city: "Spielberg",
  },
  {
    track_name: "Zandvoort",
    lat: 52.3888,
    lng: 4.5409,
    country: "Netherlands",
    city: "Zandvoort",
  },
  {
    track_name: "Circuit Zandvoort",
    lat: 52.3888,
    lng: 4.5409,
    country: "Netherlands",
    city: "Zandvoort",
  },
  {
    track_name: "Hungaroring",
    lat: 47.5789,
    lng: 19.2486,
    country: "Hungary",
    city: "Budapest",
  },
  {
    track_name: "Circuit Paul Ricard",
    lat: 43.2506,
    lng: 5.7917,
    country: "France",
    city: "Le Castellet",
  },
  {
    track_name: "Le Mans",
    lat: 47.9564,
    lng: 0.2072,
    country: "France",
    city: "Le Mans",
  },
  {
    track_name: "Circuit de la Sarthe",
    lat: 47.9564,
    lng: 0.2072,
    country: "France",
    city: "Le Mans",
  },
  {
    track_name: "Circuit de Lédenon",
    lat: 43.9314,
    lng: 4.5039,
    country: "France",
    city: "Lédenon",
  },
  {
    track_name: "Autodromo Enzo e Dino Ferrari",
    lat: 44.3439,
    lng: 11.7167,
    country: "Italy",
    city: "Imola",
  },
  {
    track_name: "Oschersleben",
    lat: 52.0289,
    lng: 11.2831,
    country: "Germany",
    city: "Oschersleben",
  },
  {
    track_name: "Motorsport Arena Oschersleben",
    lat: 52.0289,
    lng: 11.2831,
    country: "Germany",
    city: "Oschersleben",
  },
  {
    track_name: "Lausitzring",
    lat: 51.5289,
    lng: 14.1178,
    country: "Germany",
    city: "Klettwitz",
  },
  {
    track_name: "EuroSpeedway Lausitz",
    lat: 51.5289,
    lng: 14.1178,
    country: "Germany",
    city: "Klettwitz",
  },
  {
    track_name: "Norisring",
    lat: 49.4403,
    lng: 11.0753,
    country: "Germany",
    city: "Nuremberg",
  },
  {
    track_name: "Sachsenring",
    lat: 50.7917,
    lng: 12.6897,
    country: "Germany",
    city: "Hohenstein-Ernstthal",
  },
  {
    track_name: "Autodromo Internacional do Algarve",
    lat: 37.2283,
    lng: -8.6275,
    country: "Portugal",
    city: "Portimão",
  },
  {
    track_name: "Portimao",
    lat: 37.2283,
    lng: -8.6275,
    country: "Portugal",
    city: "Portimão",
  },
  {
    track_name: "Estoril",
    lat: 38.7506,
    lng: -9.3928,
    country: "Portugal",
    city: "Estoril",
  },
  {
    track_name: "Circuit de Nevers Magny-Cours",
    lat: 46.8636,
    lng: 3.1644,
    country: "France",
    city: "Magny-Cours",
  },
  {
    track_name: "Bugatti Circuit",
    lat: 47.9564,
    lng: 0.2072,
    country: "France",
    city: "Le Mans",
  },
  // ── Asia / Pacific ──────────────────────────────────────────
  {
    track_name: "Suzuka",
    lat: 34.8431,
    lng: 136.5408,
    country: "Japan",
    city: "Suzuka",
  },
  {
    track_name: "Suzuka International",
    lat: 34.8431,
    lng: 136.5408,
    country: "Japan",
    city: "Suzuka",
  },
  {
    track_name: "Twin Ring Motegi",
    lat: 36.5281,
    lng: 140.2258,
    country: "Japan",
    city: "Motegi",
  },
  {
    track_name: "Mobility Resort Motegi",
    lat: 36.5281,
    lng: 140.2258,
    country: "Japan",
    city: "Motegi",
  },
  {
    track_name: "Fuji Speedway",
    lat: 35.3717,
    lng: 138.9253,
    country: "Japan",
    city: "Oyama",
  },
  {
    track_name: "Okayama",
    lat: 34.9144,
    lng: 134.2208,
    country: "Japan",
    city: "Okayama",
  },
  {
    track_name: "Autopolis",
    lat: 33.0619,
    lng: 131.0794,
    country: "Japan",
    city: "Hita",
  },
  {
    track_name: "Tsukuba Circuit",
    lat: 36.1031,
    lng: 140.0794,
    country: "Japan",
    city: "Tsukuba",
  },
  {
    track_name: "Phillip Island",
    lat: -38.5,
    lng: 145.2333,
    country: "Australia",
    city: "Phillip Island",
  },
  {
    track_name: "Mount Panorama",
    lat: -33.4419,
    lng: 149.5594,
    country: "Australia",
    city: "Bathurst",
  },
  {
    track_name: "Bathurst",
    lat: -33.4419,
    lng: 149.5594,
    country: "Australia",
    city: "Bathurst",
  },
  {
    track_name: "Sydney Motorsport Park",
    lat: -33.8478,
    lng: 150.9906,
    country: "Australia",
    city: "Sydney",
  },
  {
    track_name: "Sepang International Circuit",
    lat: 2.7606,
    lng: 101.7381,
    country: "Malaysia",
    city: "Sepang",
  },
  {
    track_name: "Shanghai International Circuit",
    lat: 31.3397,
    lng: 121.2197,
    country: "China",
    city: "Shanghai",
  },
  {
    track_name: "Korea International Circuit",
    lat: 34.7331,
    lng: 126.4178,
    country: "South Korea",
    city: "Yeongam",
  },
  // ── Middle East / Other ─────────────────────────────────────
  {
    track_name: "Bahrain International Circuit",
    lat: 26.0325,
    lng: 50.5106,
    country: "Bahrain",
    city: "Sakhir",
  },
  {
    track_name: "Yas Marina Circuit",
    lat: 24.4672,
    lng: 54.6031,
    country: "UAE",
    city: "Abu Dhabi",
  },
  {
    track_name: "Jeddah Corniche Circuit",
    lat: 21.6319,
    lng: 39.1044,
    country: "Saudi Arabia",
    city: "Jeddah",
  },
  // ── Americas ────────────────────────────────────────────────
  {
    track_name: "Autodromo Hermanos Rodriguez",
    lat: 19.4042,
    lng: -99.0907,
    country: "Mexico",
    city: "Mexico City",
  },
  {
    track_name: "Interlagos",
    lat: -23.7036,
    lng: -46.6997,
    country: "Brazil",
    city: "São Paulo",
  },
  {
    track_name: "Autodromo José Carlos Pace",
    lat: -23.7036,
    lng: -46.6997,
    country: "Brazil",
    city: "São Paulo",
  },
  {
    track_name: "Buenos Aires",
    lat: -34.6736,
    lng: -58.4614,
    country: "Argentina",
    city: "Buenos Aires",
  },
  {
    track_name: "Canadian Tire Motorsport Park",
    lat: 44.0472,
    lng: -78.6772,
    country: "Canada",
    city: "Bowmanville, ON",
  },
  {
    track_name: "Circuit Gilles Villeneuve",
    lat: 45.5,
    lng: -73.5228,
    country: "Canada",
    city: "Montreal",
  },
  // ── Ovals / Dirt (USA) ──────────────────────────────────────
  {
    track_name: "Eldora Speedway",
    lat: 40.3589,
    lng: -84.3619,
    country: "USA",
    city: "New Weston, OH",
  },
  {
    track_name: "Knoxville Raceway",
    lat: 41.3036,
    lng: -93.1125,
    country: "USA",
    city: "Knoxville, IA",
  },
  {
    track_name: "Volusia Speedway Park",
    lat: 29.0458,
    lng: -81.3206,
    country: "USA",
    city: "Barberville, FL",
  },
  {
    track_name: "Williams Grove Speedway",
    lat: 40.1483,
    lng: -77.0358,
    country: "USA",
    city: "Mechanicsburg, PA",
  },
  {
    track_name: "Lernerville Speedway",
    lat: 40.7431,
    lng: -79.7717,
    country: "USA",
    city: "Sarver, PA",
  },
  {
    track_name: "Lincoln Speedway",
    lat: 39.9756,
    lng: -76.9883,
    country: "USA",
    city: "Abbottstown, PA",
  },
  {
    track_name: "Port Royal Speedway",
    lat: 40.5203,
    lng: -77.5383,
    country: "USA",
    city: "Port Royal, PA",
  },
  {
    track_name: "USA International Speedway",
    lat: 27.8814,
    lng: -82.3228,
    country: "USA",
    city: "Lakeland, FL",
  },
  {
    track_name: "Lucas Oil Raceway",
    lat: 39.8628,
    lng: -86.3631,
    country: "USA",
    city: "Indianapolis, IN",
  },
  {
    track_name: "Tri-Oval",
    lat: 29.1853,
    lng: -81.0694,
    country: "USA",
    city: "Daytona Beach, FL",
  },
];

/** Find coordinates for a track by name (case-insensitive partial match) */
export function findTrackCoords(trackName: string): TrackCoords | null {
  if (!trackName) return null;
  const lower = trackName.toLowerCase();
  // Exact match first
  let match = TRACK_COORDS.find((t) => t.track_name.toLowerCase() === lower);
  if (match) return match;
  // Partial match
  match = TRACK_COORDS.find(
    (t) =>
      lower.includes(t.track_name.toLowerCase()) ||
      t.track_name
        .toLowerCase()
        .includes(lower.split(" ").slice(0, 3).join(" ")),
  );
  return match ?? null;
}
